"""creating tables

Revision ID: 485c4e25b2e3
Revises: f9be43de3ebe
Create Date: 2022-07-28 18:10:16.383822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485c4e25b2e3'
down_revision = 'f9be43de3ebe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
