"""finalizing tables

Revision ID: 4e86117ce3a2
Revises: 485c4e25b2e3
Create Date: 2022-07-28 18:26:13.653476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e86117ce3a2'
down_revision = '485c4e25b2e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
